### ISSUE TITLE
fit_ssm bug

### ISSUE THREAD

**Issue by malcolm-otoole** [ianjonsen/foieGras#12]
Hi Ian 

I am getting the following error message from the fit_ssm function:
**Error in optim(par = c(logD = 10, l_psi = 0, l_tau = 0, l_tau = 0, l_rho_o= 0 : L-BFGS-B needs finite values of 'fn'**

Here is the code I used:
`fit_ssm(df2, model='crw', vmax=3, time.step=24)`

The problem could be because the raw data are generated from simulated tracks:
[test_track.txt](https://github.com/ianjonsen/foieGras/files/4286137/test_track.txt)
[test_track_2.txt](https://github.com/ianjonsen/foieGras/files/4286139/test_track_2.txt)

Any thoughts would be appreciated.
Cheers

Malcolm

**Comment by ianjonsen** [comment]
for simulated tracks, the psi parameter should be fixed as it is irrelevant for simulated error ellipses. Parameters can be fixed (turned off) via the `map` argument:

`fit <- fit_ssm(df2, model = "crw", vmax = 3, time.step = 24, map = list(psi = as.factor(NA))`

**Comment by ianjonsen** [comment]
Need to investigate why some `time.step` choices work and some cause optimiser crashes...

**Comment by makratofil** [comment]
Hi Ian,

I've also been running into this issue for a couple of tags that I'm working with, but interestingly only when running "rw" model (am comparing outputs of the two models). The error I'm getting is:
**Error in optim(par = c(l_sigma = -1.32296036415467, l_sigma = -1.40533393138059, : L-BFGS-B needs finite values of 'fn'**

I've been specifying a ~5 minute time step, which is what we are wanting for our project objectives, but don't get the error when I run a 10 minute time step. All but two tags I've been working with have run with a 5 min time step just fine. 

Here is my code:
`fit_ssm(locs, spdf = F, model = "rw", time.step = 0.083, verbose = 1)`

And here is the location file for one of the tags that has been giving me this error:
[TtTag034_Locations.xlsx](https://github.com/ianjonsen/foieGras/files/4331733/TtTag034_Locations.xlsx)

Let me know if this helps and if you find anything!

Michaela

**Comment by ianjonsen** [comment]
Thanks for your data @makratofil. I'll take a look soon. 

Just a tip for future postings, link to .RDS, .csv / .txt files rather than .xlsx! the latter can brutalise date/time formats when crossing platforms, locales, etc...

cheers, ian

**Comment by SamLCox** [comment]
Hi Ian,
I am also getting a lot of optimiser crashes similar to those mentioned above, and just want to check if they are related to user error (I updated foieGras late last week from github so think I am on the most up to date version).  I am using foieGras for 2 discrete purposes ('rw' option, but I have similar issues with 'crw') - (1) to regularise GPS data, and fill in a few small gaps, and (2) to get location estimates corresponding to a series of irregular timestamps from dive events.  Most of my data is at a resolution of 10-20 minutes, with some gaps of up to one hour.  With regards to Aim 1, I am trying to regularise to set 15 minute intervals.  If I do this across the entire dataset, the model fits, but I get huge SE's on the rho_o parameter.  If I try to fit the model to data which has been split into continuous chunks, corresponding to periods with gaps no greater than 80 minutes between successive GPS fixes (chunks are also at least 1 hour long with +7 GPS fixes), I run into issues with the optimiser.  With regards to aim 2, I am getting warnings returned relating to the production of NaN's on the object$diag.cov.random - and following this the estimate of rho_o is a NaN.  Is there something I am missing here, or do I simply need to reduce resolution and abandon attempts to fit to irregular time series (it would be preferable to keep to the high resolution/irregular predicting)?  I can provide my script/.rds files if you think it is useful?  
Thank you in advance for any help/tips you can provide.  
Cheers
Sam

**Comment by ianjonsen** [comment]
Hi Sam, If fitting the `rw` model, you might try your approach but turn off estimation of the `psi` parameter by including the following argument: `map = list(psi = as.factor(NA))`. If that doesn't solve either the issues with either aim 1 or 2 then send me the script and .rds file and I'll see if I can fix it. Cheers, ian

**Comment by ianjonsen** [comment]
Hi Michaela,

Your example converges without error when using the latest version, 0.6-7. In this version, estimation of the semi-minor axis scaling factor (`psi`) is turned off for `model = "rw"` by default. Note that turning off the prefilter with `spdf = FALSE` can lead to convergence issues for some tracks. Also, your specified `time.step` leads to quite extreme interpolation given the typical time between observed locations.

The latest version probably won't be available on CRAN until sometime on the week of 15 June. Until then you can install from the master repo.

Best, Ian

**Comment by ianjonsen** [comment]
Closing this as latest release should address this issue.

**Comment by SamLCox** [comment]
Hi Ian,
Just wanted to say thanks very much for the reply.  I did try what you recommended: turning off the psi parameter but still had the same issue.  I am now investigating a bit more in-depth the data structure I have, as I think it makes sense to fit the model to the continuous data-stream and then predict to set points within continuous chunks.  This was working better, but when I try and predict to the times of dives I get errors again.  Anyway I will try running this through the latest updated package - which hopefully will work.  Will start a new thread if there is an issue.  Sorry about the lag in my response to your response. Cheers
