### ISSUE TITLE
Errors fitting GPS data  version 0.4.0

### ISSUE THREAD

**Issue by istaniland** [ianjonsen/foieGras#15]
Hi Ian,
Not a bug most likely user error!
I am getting the following error when I try to fit GPS data

fit_ssm(gps,vmax = 3,model = "crw",time.step = 10)

pre-filtering data...

fitting SSM...
Error in optim(par = c(logD = 10, l_rho_o = 0), fn = function (x = last.par[-random],  : 
  L-BFGS-B needs finite values of 'fn'
Error in optimHess(par.fixed, obj$fn, obj$gr) : 
  gradient in optim evaluated to length 1 not 2
# A tibble: 1 x 3
  id    ssm    converged
  <chr> <list> <lgl>    
1 W8254 <ssm>  FALSE    

Any pointers appreciated!

Cheers

Iain Staniland

**Desktop :**
 -  Windows 10
 - RStudio
 - R VersionR-3.6.1

[FoiegrasGPS.zip](https://github.com/ianjonsen/foieGras/files/4394757/FoiegrasGPS.zip)

**Comment by ianjonsen** [comment]
Hi Iain, Hmm, you did find a wee bug in the `prefilter` code; GPS locations weren't getting assigned appropriately. I've added a temporary fix to the dev version, which you can get via:

`remotes::install_github("ianjonsen/foieGras@dev")`

Thanks for pointing this out. Cheers, Ian

**Comment by istaniland** [comment]
Hi Ian,
Thank you
However I now get the error message


> fit_ssm(gps,vmax = 3,model = "crw",time.step = 10)



pre-filtering data...



fitting SSM...

Error in optim(par = c(logD = 0, l_rho_o = 0), fn = function (x = last.par[-random],  :

  L-BFGS-B needs finite values of 'fn'

Error in optimHess(par.fixed, obj$fn, obj$gr) :

  gradient in optim evaluated to length 1 not 2

# A tibble: 1 x 3

  id    ssm    converged

  <chr> <list> <lgl>

1 W8257 <ssm>  FALSE





Cheers



Iain





Full run:

-- Attaching packages --------------------------------------- tidyverse 1.3.0 --

v ggplot2 3.2.1     v purrr   0.3.3

v tibble  2.1.3     v dplyr   0.8.3

v tidyr   1.0.0     v stringr 1.4.0

v readr   1.3.1     v forcats 0.4.0

-- Conflicts ------------------------------------------ tidyverse_conflicts() --

x dplyr::filter() masks stats::filter()

x dplyr::lag()    masks stats::lag()

> library(foieGras)

>

> #vignette("foiegras-basics")

> #C:\Users\ijst\OneDrive - NERC\GPS data\2005-2006

>

> path_to_file <- "C:\\Users\\ijst\\OneDrive - NERC\\GPS data\\2011-2012\\"

> gps <- read_csv(file=paste0(path_to_file,"W8257_140112.csv"))

Parsed with column specification:

cols(

  Date = col_character(),

  Time = col_time(format = ""),

  `No of satellites used` = col_double(),

  Latitude = col_double(),

  Longitude = col_double(),

  Altitude = col_double(),

  `Clock offset` = col_double(),

  `Accuracy indicator` = col_double(),

  `Battery indicator` = col_double()

)

>

> #Date Time    No satellites used     Latitude       Longitude      Altitude       Clock offset       Accuracy indicator     Battery voltage

> #join date and time together

>

> gps <- gps %>% mutate(date = as.POSIXct(strptime(paste(Date,Time),format = "%d/%m/%Y %H:%M:%S", tz = "GMT"))

+                       ,lon = Longitude,lat = Latitude,id = "W8257", lc = "G") %>%

+    filter(`Accuracy indicator` <= 100) %>%

+   select(id,date,lc,lon,lat)

> fit_ssm(gps,vmax = 3,model = "crw",time.step = 10)



pre-filtering data...



fitting SSM...

Error in optim(par = c(logD = 0, l_rho_o = 0), fn = function (x = last.par[-random],  :

  L-BFGS-B needs finite values of 'fn'

Error in optimHess(par.fixed, obj$fn, obj$gr) :

  gradient in optim evaluated to length 1 not 2

# A tibble: 1 x 3

  id    ssm    converged

  <chr> <list> <lgl>

1 W8257 <ssm>  FALSE




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ianjonsen** [comment]
Ugh, sorry. Should be all fixed now, your example works for me. All updates are now in the master branch - install_github("ianjonsen/foieGras") will install the fixes for you.

**Comment by istaniland** [comment]
Thanks Ian,
Updated package from Github and worked beautifully on all three datasets

Cheers Again

Iain

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
