### ISSUE TITLE
Track segment anomalies when using CRW

### ISSUE THREAD

**Issue by hallegue** [ianjonsen/foieGras#16]
Hi there,

I fitted an ssm model with crw on 100 seal Argos locs to filter the data. 
```
  fit <- foieGras::fit_ssm(d = dt, time.step  = time.step, model = "crw", vmax = 4)
```
with R (version 3.6.3) and: 
```
foieGras      0.4.01-3   2020-04-03 [1] Github (ianjonsen/foieGras@35f87db) 
```

Overall the fit seems appropriate. See an example here:

![goo_track](https://user-images.githubusercontent.com/14200886/78999482-41c57280-7b3a-11ea-86fa-045cded40d30.png)

However, in some case, especially when the seal track has segments with low loc densities, some anomalies appear which are unlikely representing the true seal movement. See an example here (red arrows are pointing these anomalies):

![Bad_1](https://user-images.githubusercontent.com/14200886/78999628-8e10b280-7b3a-11ea-8965-8ce8e24a97f8.png)
  
![Bad_2](https://user-images.githubusercontent.com/14200886/78999635-923cd000-7b3a-11ea-8411-e6889498357c.png)
 
As an example, here the dataset of the seal `F06-B-18_1` showed above:

[F06-B-18_1_data.txt](https://github.com/ianjonsen/foieGras/files/4462060/F06-B-18_1_data.txt)

And the results of the model fit:
```
Process model: crw 
Time interval: 1 hours 
number of observations: 4566 
number of regularised state estimates: 1885 

parameter estimates
-------------------
      Estimate Std. Error
D        5.290      0.119
rho_o    0.187      0.026
tau      0.067      0.001
tau      0.059      0.001
psi      8.083      0.977
-------------------
negative log-likelihood: 2067.689 
convergence: CONVERGENCE: REL_REDUCTION_OF_F <= FACTR*EPSMCH 
```
I feel this issue appears in track segments when locations are at very low density. I guess that the correlation value is to high for these segments and results in some track anomalies/deviations. Yes I could just use a random walk model but is there a way to control and lower the correlation value or have a correlation value that is adjusted according to time difference between locations? 

I tried this to set the initial value of Rho_o: 

```
  fit <- foieGras::fit_ssm(d = dt, 
           time.step  = time.step, 
           model = "crw", 
           vmax = 4, 
            parameters = list(rho_o = 0.1))
```

But I've got this error: 
```
fitting SSM...
Error in x$data : $ operator is invalid for atomic vectors
In addition: Warning message:
In MakeADFun(data, parameters, map = map, random = rnd, hessian = FALSE,  :
  Expected object. Got NULL.
```
Not sure how to specify initial values of parameters. 

Any suggestions or recommendations of how to fix this?

Thanks so much.

Hassen

**Comment by ianjonsen** [comment]
Hi Hassen,

Those artefacts generally occur when observation frequency is low _relative_ to the prediction time interval. You should reduce the prediction interval (via `time.step` argument) to reduce the severity of those artefacts. 

Specifying different initial values for parameters generally won't result in substantially different fits to the data. The option to specify different parameter initial values exists to deal with cases where the optimizer may not converge using the default values. The parameters are specified on the log or logit scale, so in your example you would use `parameters = list(l_rho_o = 0.1)` but this won't have any noticeable impact on those artefacts - `rho_o` is the the correlation between `x` and `y` error variances (ie. `tau_x^2`, `tau_y^2`).

Ian

**Comment by hallegue** [comment]
Thanks Ian! Ok, I'll just lower the time step then.
