### ISSUE TITLE
Allow non POSIX date sequences

### ISSUE THREAD

**Issue by hjftan** [ianjonsen/foieGras#24]
**Is your feature request related to a problem? Please describe.**

When im specifying the Argos date into POSIX format the date time combination of "25/03/2018 01:42" is returning NA with as.POSIXct(). With as.POSIXlt() the "correct" date string is returned, however, oddly is.na() returns NA for that entry (not others).

I suspect this is due to some timezone/clock changing thing in the study region.

This doesn't seem to cause any particular issues with foiegras itself.

However, I would like to use an irregular time interval within the time.step argument, which has a POSIX requirement.
When generating the time interval I would like to use, this POSIX related NA problem is causing some problems. 

**Describe the solution you'd like**

It would be useful if I could define an arbitrary time sequence to define record order within the time.step argument

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ianjonsen** [comment]
If the irregular time interval you want to use corresponds to the Argos observation times, then `time.step = NA` will estimate fitted values only, at the (irregular) observation times. If you want some more arbitrary irregular time sequence then can you provide me with some reproducible code to better illustrate the problem? I don't get the error you seem to be having with `as.POSIXct("25/03/2018 01:42", format="%d/%m/%Y %H:%M")` or `as.POSIXct("25/03/2018 01:42", format="%d/%m/%Y %H:%M", tz = "UTC")`. 

thanks
