### ISSUE TITLE
Can't load foieGras after R update to 4.1.0

### ISSUE THREAD

**Issue by AThielecke** [ianjonsen/foieGras#26]
I updated R to Version 4.1.0 and am now unable to load the foieGras package. Alle other packages seem to be working fine.
I've tried downloading the package and it seems to work
![image](https://user-images.githubusercontent.com/84733402/119380541-c6c90800-bcb8-11eb-8f62-60d86e15c766.png)

However, when trying to load the package I get the following error message:
![image](https://user-images.githubusercontent.com/84733402/119380633-e2cca980-bcb8-11eb-9fc9-633a4256c7cd.png)

These are my settings:
![image](https://user-images.githubusercontent.com/84733402/119380881-fc6df100-bcb8-11eb-87ce-22891ac29b1a.png)

I am relatively inexperienced with R and would appreciate any help. 
Thanks in advance. 
A

**Comment by ianjonsen** [comment]
I think you are missing the `gmm` package, which is not a direct dependency for foieGras but appears to be for one or more of the  packages that foieGras imports. Try `install.packages("gmm")` and then restart R and reload foieGras

**Comment by AThielecke** [comment]
Problem solved:
I lacked an installation of gfortran8.2 (https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/8.2) which is required for the newest update of R
