### ISSUE TITLE
Failing to fit jmpm model

### ISSUE THREAD

**Issue by paolagab** [ianjonsen/foieGras#29]
Hi Ian,

I'm working with shark Argos tracking data. I have no problems when trying to fit the crw model to the data using the function fit_ssm as follows:

    fit <- fit_ssm(tbl, vmax = 2, ang = c(15, 25), model = "crw", time.step = 12, 
               control = ssm_control(se=FALSE))

But when I try to fit the jmpm model (as the selected mpm model) for one species using the function fit_mpm, I get an error. This is the code for the fit_mpm function I used and the error I got:

     fmp <- fit_mpm(fit, optim = "optim", what = "predicted", model = "jmpm", control = mpm_control(verbose = 0), coords=4:5)

    

     Error in nlminb(obj$par, ifelse(control$verbose == 1, myfn, obj$fn), obj$gr,  : 
      NA/NaN gradient evaluation

     Error in optimHess(par.fixed, obj$fn, obj$gr) : 
      gradient in optim evaluated to length 1 not 3

From reading the package manual, I think that it might have something to do with the control argument, but I'm not sure why nor how to fix it.

When I run the code for each track separately, I don't get any errors. Within the data set, there are tracks with quite different longitude data (ranging from ~-80º to 8º). I don't know if that is also a problem when analyzing all tracks together.

This is my first time analyzing this type of data and I am quite inexperienced with R, so I would appreciate any help.

Paola

**Comment by paolagab** [comment]
Hi Ian,

Okay, I'll go with the mpm fits then. Thank you for the explanation and for your help! 

Paola

**Comment by fooxhd** [comment]
Hi Ian,

I'm trying to `fit_mpm` on southern elephant seal tracks. 

I also had the same problem as Paola when I fitted all the animals together in a `jmpm` so I tried fitting them 1 by 1 instead as an `mpm`. It worked for most but still had some individuals which failed to converge.

My code for e.g. one of the failed individuals
```
fit <- foieGras::fit_ssm(d3 %>% filter(id == 'mq4-Billie-00'),
                         vmax = 4,
                         map = list(psi = factor(NA)),
                         model = "crw",
                         time.step = 24)

fit_mpm(fit, what = "predicted", model = "mpm", control = mpm_control(verbose = 0))
```

and the output from the code above:
```
Error in nlminb(obj$par, ifelse(control$verbose == 1, myfn, obj$fn), obj$gr,  : 
  NA/NaN gradient evaluation

# A tibble: 1 × 4
  id            mpm            converged model
  <chr>         <named list>   <lgl>     <chr>
1 mq4-Billie-00 <try-errr [1]> FALSE     mpm  

```

When I check what's the `try-errr[1]` under the `mpm` column:
```
$`mq4-Billie-00`
[1] "Error in opt[[\"par\"]] : subscript out of bounds\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in opt[["par"]]: subscript out of bounds>
```



Are there any possible solutions from this point? I've tried changing the pre-filtering `vmax = 2` but didn't make a difference.

I'm also not familiar with how to tweak the `mpm_control` settings so any help is greatly appreciated!

**Comment by ianjonsen** [comment]
Hi Dahlia,

I'd need to see the data, or a subset that produces the error to see if there's a solution. 

Thanks, Ian

**Comment by fooxhd** [comment]
Hi Ian,

I wanted to try testing different `vmax` and `timestep`  inputs into `fit_ssm` first as I realise they affect the model convergence for `fit_mpm`. I've settled at `vmax = 4` and `timestep = 4`. 

When I use a different vmax the individuals that failed to converge during the mpm step varies - so I'm wondering if using a different `vmax` only for problem individuals is advisable? 

In any case I've attached the data for the problem seals. 

[ses_mpmfailed.rds.zip](https://github.com/ianjonsen/foieGras/files/7646290/ses_mpmfailed.rds.zip)


> Hi Dahlia,
> 
> I'd need to see the data, or a subset that produces the error to see if there's a solution.
> 
> Thanks, Ian

**Comment by ianjonsen** [comment]
Sorry for delayed response, Dahlia. Using foieGras 1.0.0 (currently on GitHub only), I can get both the `crw` SSM and the `jmpm`  to converge successfully when fitting to all 3 tracks and using `vmax=4, time.step=4`. However, I'd say the first individual's track is a bit too short to infer anything sensible with `fit_mpm`, and the 4-h time.step is probably too short for mpm inference (as per the figure below), a 6- or 12-h timestep would probably be more appropriate.

![Rplot](https://user-images.githubusercontent.com/9984184/146052658-1ed6d9f3-f905-47e6-9606-047911538171.png)

**Comment by fooxhd** [comment]
Thanks Ian! Using v.1.0.0 and changing it to a 12h time step worked for every seal.

**Comment by pictuswolf** [comment]
Hi 
I am having a similar error when using the fit_ssm function, I just cant work out how to resolve...
I too am a newbie to R so any explicit code to help me resolve this would be appreciated

The code is as follows:

#### Account for location error at observed irregular time interval ####

fit_crw_fitted <- fit_ssm(dat2, vmax = 1, model = "crw", time.step = NA,
                          control = ssm_control(verbose = 1))
map = list(rho_o = factor(NA)) 

print(fit_crw_fitted)



> # Estimate 'true' locations on irregular sampling interval (by setting `time.step = NA`)
> fit_crw_fitted <- fit_ssm(dat2, vmax = 1, model = "crw", time.step = NA,
+                           control = ssm_control(verbose = 1))
fitting crw SSM to 2 tracks...
 pars:   0 0 0 0      Error in nlminb(obj$par, ifelse(control$verbose == 1, myfn, obj$fn), obj$gr,  : 
  NA/NaN gradient evaluation

 pars:   0 0 0 0      Error in nlminb(obj$par, ifelse(control$verbose == 1, myfn, obj$fn), obj$gr,  : 
  NA/NaN gradient evaluation
In addition: Warning message:
The optimiser failed. Try simplifying the model with the following argument: 
                                 map = list(rho_o = factor(NA)) 

Warning message:
The optimiser failed. Try simplifying the model with the following argument: 
                                 map = list(rho_o = factor(NA))  
> map = list(rho_o = factor(NA)) 
> 
> print(fit_crw_fitted)
# A tibble: 2 × 5
  id    ssm          converged pdHess pmodel
  <chr> <named list> <lgl>     <lgl>  <chr> 
1 C5978 <ssm [7]>    FALSE     FALSE  crw   
2 C5979 <ssm [7]>    FALSE     FALSE  crw   

[All_example.csv](https://github.com/ianjonsen/aniMotum/files/10917006/All_example.csv)

**Comment by ianjonsen** [comment]
Thanks for providing the output and `All_example.csv` file, but I'l need to see your code that goes from reading in `All_example.csv` through to generating `dat2` - the data input to `fit_ssm()` in your above example.

**Comment by pictuswolf** [comment]
Hi Ian,
Thanks so much for looking at this. I'm sure it's a simple fix but I just don't have the background yet to work through it. If you can let me know in a 'R for Dummies' type of way that would be of benefit.
Warm regards,

Nikki Anderson | Cert IV VN, BSc (Biod Cons), Bach. Applied GIS (Hons 1st Class), PhD
Conservation biologist/independent researcher
M: +61415 745 419 |  E: ***@***.******@***.***>
Associate Lecturer | College of Science and Engineering, Flinders University of South Australia
Research co-ordinator | Kalahari African Wild Dog Conservation Trust

**Comment by salomejg** [comment]
Hi, I'm having a similar "warning" with the package aniMotum 

#Date must be in "POSIXct" "POSIXt" 
Data$local_time <- as.POSIXct(Data$local_time, format = "%m/%d/%Y %H:%M")  
class(Data$local_time)

# Correlated Random Walk Filter:
df_obseervat <- as_tibble(data.frame(
  id = Data$Argos_ID,
  date = Data$local_time,
  lc = Data$Quality,
  lon = Data$Lon,
  lat = Data$Lat))

## use only 1 shark track
df_obseervat_1 <- subset(df_obseervat, id == "174288")

fit.rw <- aniMotum::fit_ssm(df_obseervat_1, model = "rw", time.step = 12)

and the warning are:

Warning: NA/NaN function evaluationError in nlminb(obj$par, ifelse(control$verbose == 1, myfn, obj$fn), obj$gr,  : 
  NA/NaN gradient evaluation

Warning: The optimiser failed. Try simplifying the model with the following argument: 
                                 map = list(rho_o = factor(NA))

any idea what is happening?
