### ISSUE TITLE
Error loading `foieGras` for M1/M2 chip macs 

### ISSUE THREAD

**Issue by dahliasan** [ianjonsen/foieGras#37]
Hi Ian, I'm using foiegras as part of a practical class for students and those who are using the newer macs with M1 or M2 chips are getting this error when they run `library(foieGras)`

```
Error: package or namespace load failed for ‘foieGras’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/gmm/libs/gmm.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/gmm/libs/gmm.so, 0x0006): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.2/Resources/library/gmm/libs/gmm.so
  Reason: tried: '/usr/local/gfortran/lib/libgomp.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Library/Frameworks/R.framework/Resources/lib/libgomp.1.dylib' (no such file), '/Users/kaitlyn/lib/libgomp.1.dylib' (no such file), '/usr/local/lib/libgomp.1.dylib' (no such file), '/usr/lib/libgomp.1.dylib' (no such file), '/lib/libgomp.1.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/server/libgomp.1.dylib' (no such file), '/va
```

Not all of them have the exact same error (some more than others), but the common error among them is this part:
```
Error: package or namespace load failed for ‘foieGras’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/gmm/libs/gmm.so':
dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/gmm/libs/gmm.so, 0x0006): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
```

 - OS: MacOS >= 12 (Monterey) 
 - RStudio (latest version RStudio Desktop 2022.07.1+554)
 - R Version (4.2)

**Comment by ianjonsen** [comment]
The error appears to be occurring because they don't have a fortran compiler installed (or an incorrect one for M1/M2 Macs).  The latest version for M1/M2 Macs can be downloaded from here: 

[gfortran-ARM-12.1-Monterey.dmg](https://github.com/fxcoudert/gfortran-for-macOS/releases/download/12.1-monterey/gfortran-ARM-12.1-Monterey.dmg)

once installed, foieGras should install without error.

Ian

**Comment by dahliasan** [comment]
Thanks Ian, I did try that for one of the student's computer where I installed gfortran for ARM computers and the first error output was still printed. It'll be hard to continue troubleshooting since I don't have the student's computer anymore so I think we can close this issue for now. Hopefully it'll work for other computers!
