### ISSUE TITLE
Huge outliers

### ISSUE THREAD

**Issue by otoolem** [ianjonsen/foieGras#5]
Hi Ian

I fit GPS locations (error < 100 m) to the foieGras model without too much trouble, except that the location output of some individuals exhibit a large outlier that deviates 500-1500 km from its neighbors. Interestingly, most of these outliers occur on day 2 (model timestep is 24 h).

`fit=fit_ssm(data, model='crw', vmax=3, time.step=24)`

The same tracks put through the speed filter, but not the SSM, exhibit no such outliers. I have included some example maps. Any thoughts?

Cheers

Malcolm

![SSMOutlierMap-1](https://user-images.githubusercontent.com/5524284/55706574-1e8e5180-5a14-11e9-905c-b482a6567e7e.jpeg)
![SSMOutlierMap-2](https://user-images.githubusercontent.com/5524284/55706599-2cdc6d80-5a14-11e9-83d6-2a88bab67870.jpeg)
![SSMOutlierMap-5](https://user-images.githubusercontent.com/5524284/55706628-3bc32000-5a14-11e9-88c9-5a57d72e596e.jpeg)

**Comment by ianjonsen** [comment]
Hmm, I'm not sure, Malcolm. Can you give me a reproducible example, ie. enough data to fit the model?

**Comment by otoolem** [comment]
Hi Ian

I have tried to re-run fit_ssm to investigate the problem of outliers but it no longer gives me the correct output. If I apply the speed filter I receive a warning message: Unknown or uninitialised column: 'data'. If I apply the crw model I get output without predicted lon/lat columns (fit$data has no lon/lat columns). I’ve attached some data, and the code I use is below.

fit1=fit_ssm(d, vmax=3, time.step=24, pf=TRUE)
fit2=fit_ssm(d, vmax=3, time.step=24, model='crw')

I have tried running foieGras on different versions of R and still no luck. I wonder if I am missing crucial packages (I re-installed TMB and Matrix and still nothing).

Any thoughts?

Cheers

Malcolm



Malcolm O’Toole
UWA Research Associate

IOMRC building Room 2.45 1
Cnr Fairway and Service Road 4 (M470)
The University of Western Australia
35 Stirling Highway, Crawley
Western Australia 6009

Phone: +61 8 6488 3529
Mobile: +61 (0)439 440 653
Email: malcolm.otoole@uwa.edu.au

________________________________

**Comment by ianjonsen** [comment]
It's not you, it's me. think I broke prefilter when pf = TRUE as I got the same error late yesterday. I'll work on a fix and then we can get back to the issue of the strange estimates

**Comment by otoolem** [comment]
Thanks Ian. Much appreciated.
Cheers
Malcolm


Malcolm O’Toole
UWA Research Associate

IOMRC building Room 2.43
Cnr Fairway and Service Road 4 (M470)
The University of Western Australia
35 Stirling Highway, Crawley
Western Australia 6009

Phone: +61 8 6488 3529
Mobile: +61 (0)439 440 653
Email: malcolm.otoole@uwa.edu.au

________________________________

**Comment by ianjonsen** [comment]
Hi Malcolm, given your recent email re: outlier estimates no longer occurring, are you happy for me to close this issue? thanks, Ian

**Comment by otoolem** [comment]
Hi Ian. Yes that was very helpful. All sorted now. Thanks

Malcolm O’Toole
UWA Research Associate

IOMRC building Room 2.43
Cnr Fairway and Service Road 4 (M470)
The University of Western Australia
35 Stirling Highway, Crawley
Western Australia 6009

Phone: +61 8 6488 3529
Mobile: +61 (0)439 440 653
Email: malcolm.otoole@uwa.edu.au

________________________________
